version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - postgres
      - redis

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=squares
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  lb:
    image: dockercloud/haproxy
    links:
      - server
      - client
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
