version: '3'
services:
  client:
    build: ./client
    ports:
      - "5000"
    environment:
      - "REACT_APP_BACKEND_URI=localhost:4000"
  server:
    build: ./server
    ports:
      - "4000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=squares
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql